trends/config/routes.rb
Rails.application.routes.draw do
  get '/trends/search' => 'trends#search'
  resources :trends do
    collection do
      post 'search'
    end
  end

end

trends/app/models/trend.rb
class Trend < ActiveRecord::Base

	private

  def user_params
    params.require(:trendid, :title, :price, :quantity)
  end
end

trends/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

trends/app/controllers/trends_controller.rb
class TrendsController < ApplicationController
	def index
		@trends = Trend.all
	end
	def show
		@trend = Trend.find(params[:id])
	end
	def new
		 @trend = Trend.new
	end
	def create
		@trend = Trend.create!(trend_params)
		flash[:notice] = "#{@trend.trendid} was successfully created."
		redirect_to trends_path
	end
	def edit
		@trend = Trend.find params[:id]

	end
	def search
		# @trend = Trend.find("3")
		t = Trend.find_by(:trendid =>params[:trendid])
		if t
			@trend = t
		else
			redirect_to trends_path
			flash[:notice] = "No record found"
		end

	end
	def update
		@trend = Trend.find params[:id]
		@trend.update_attributes!(trend_params)
		flash[:notice] = "#{@trend.title} was successfully updated."
		redirect_to trends_path(@trend)
		 
	end
	def destroy
		@trend = Trend.find(params[:id])
		@trend.destroy
		flash[:notice] = "Trend '#{@trend.title}' deleted."
		redirect_to trends_path
	end

	private

	def trend_params
			params.require(:trend).permit(:title, :trendid, :price, :quantity)

	end
end

trends/app/helpers/application_helper.rb
module ApplicationHelper
end

trends/app/helpers/trends_helper.rb
module TrendsHelper
end

trends/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trends</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<% flash.each do |key, value| %>
  <p><%= value %></p>
<% end %>

</body>
</html>

trends/app/views/trends/edit.html.haml
%h1 Edit existing  Trend

= form_tag trend_path(@trend), :method => :put do

  = label :trend, :title, 'Title'
  = text_field :trend, 'title'

  = label :trend, :trendid, 'Trendid'
  = text_field :trend, 'trendid'

  = label :trend, :price, 'Price'
  = text_field :trend, 'price'

  = label :trend, :quantity, 'Quantity'
  = text_field :trend, 'quantity' 

  = submit_tag 'Update trend Info'

trends/app/views/trends/index.html.haml
-# This file is app/view/trends/index.html.haml
= form_tag search_trends_path do
  = text_field_tag :trendid, params[:trendid],:id =>'search_field'
  = submit_tag 'Search', :name =>nil


%h1 All Trends

%table#trends
  %thead
    %tr
      %th articleid
      %th{:class => @title_}
        %a{:id => "title_header"}= link_to "Trend Title", trends_path(:column_index => "title"),:sort_by=>"title"
      %th price
      %th quantity
  %tbody
    - @trends.each do |trend|
      %tr
        %td= trend.trendid
        %td= trend.title
        %td= trend.price
        %td= trend.quantity
        %td= link_to "more about #{trend.title}", trend_path(trend)

= link_to 'Add new trend', new_trend_path 

= link_to 'Search' , search_trends_path

trends/app/views/trends/new.html.haml
%h1 Create New Trend

= form_tag trends_path do

  = label :trend, :title, 'Title'
  = text_field :trend, 'title'

  = label :trend, :trendid, 'Trendid'
  = text_field :trend, 'trendid'

  = label :trend, :price, 'Price'
  = text_field :trend, 'price'

  = label :trend, :quantity, 'Quantity'
  = text_field :trend, 'quantity' 

  = submit_tag 'Save Changes'

trends/app/views/trends/search.html.haml
%h1 Details about #{@trend.trendid}

%ul#details
  %li
    title:
    = @trend.title
  %li
    price:
    = @trend.price
  %li
    quantity:
    = @trend.quantity

= link_to 'Back to trend list', trends_path

trends/app/views/trends/show.html.haml
-# in app/views/trends/show.html.haml

%h1 Details about #{@trend.trendid}

%ul#details
  %li
    title:
    = @trend.title
  %li
    price:
    = @trend.price
  %li
    quantity:
    = @trend.quantity


= link_to 'Edit info', edit_trend_path(@trend)
= button_to 'Delete', trend_path(@trend), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to trend list', trends_path